# ???? WEB ????
server.port=8080

# ?????
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_management?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis Plus??
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.global-config.db-config.id-type=auto
mybatis-plus.mapper-locations=classpath*:/mapper/**/*.xml
mybatis-plus.type-aliases-package=com.example.keshe1.entity
mybatis-plus.configuration.map-underscore-to-camel-case=true

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
spring.servlet.multipart.enabled=true


spring.web.resources.cache.period=3600
spring.web.resources.chain.strategy.content.enabled=true
spring.web.resources.chain.strategy.content.paths=/**


spring.web.resources.static-locations=classpath:/static/,classpath:/public/,file:${user.dir}/uploads/


logging.level.com.example.keshe1.config.WebConfig=DEBUG
logging.level.com.example.keshe1.controller.PatientController=DEBUG

server.tomcat.basedir=./tomcat-temp

server.tomcat.resource.cache-ttl=0

doubao.api.key=c8b0b818-3b5d-4cba-9a2e-1b3bb2efebfc
doubao.api.endpoint=https://ark.cn-beijing.volces.com/api/v3/chat/completions
doubao.model=doubao-1.5-pro-32k-250115

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
# ???????
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
